### ISSUE TITLE
Path to Raku (meta issue)

### ISSUE THREAD

**Issue by samcv** [perl6/atom-language-perl6#95]
- [ ] Find all atom packages relying on script name "Perl 6"
I am not sure how to do this, HELP WANTED
- [ ] Find all atom package relying on scopeName "source.perl6fe"
This is a nice searchable way to find things relying on this package since it's a very searchable string. It is not decided yet if we want to rename the scope, but a list of affected packages would allow us to make an informed decision.
- [ ] Rename language-perl6 to language-raku with an atom package release (@samcv can do this when the time comes)
- [ ] Ask language-perl to remove their perl6 syntax highlighter
